require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuickQuotesController do

  # This should return the minimal set of attributes required to create a valid
  # QuickQuote. As you add validations to QuickQuote, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all quick_quotes as @quick_quotes" do
      quick_quote = QuickQuote.create! valid_attributes
      get :index
      assigns(:quick_quotes).should eq([quick_quote])
    end
  end

  describe "GET show" do
    it "assigns the requested quick_quote as @quick_quote" do
      quick_quote = QuickQuote.create! valid_attributes
      get :show, :id => quick_quote.id.to_s
      assigns(:quick_quote).should eq(quick_quote)
    end
  end

  describe "GET new" do
    it "assigns a new quick_quote as @quick_quote" do
      get :new
      assigns(:quick_quote).should be_a_new(QuickQuote)
    end
  end

  describe "GET edit" do
    it "assigns the requested quick_quote as @quick_quote" do
      quick_quote = QuickQuote.create! valid_attributes
      get :edit, :id => quick_quote.id.to_s
      assigns(:quick_quote).should eq(quick_quote)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuickQuote" do
        expect {
          post :create, :quick_quote => valid_attributes
        }.to change(QuickQuote, :count).by(1)
      end

      it "assigns a newly created quick_quote as @quick_quote" do
        post :create, :quick_quote => valid_attributes
        assigns(:quick_quote).should be_a(QuickQuote)
        assigns(:quick_quote).should be_persisted
      end

      it "redirects to the created quick_quote" do
        post :create, :quick_quote => valid_attributes
        response.should redirect_to(QuickQuote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quick_quote as @quick_quote" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuickQuote.any_instance.stub(:save).and_return(false)
        post :create, :quick_quote => {}
        assigns(:quick_quote).should be_a_new(QuickQuote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuickQuote.any_instance.stub(:save).and_return(false)
        post :create, :quick_quote => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quick_quote" do
        quick_quote = QuickQuote.create! valid_attributes
        # Assuming there are no other quick_quotes in the database, this
        # specifies that the QuickQuote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuickQuote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => quick_quote.id, :quick_quote => {'these' => 'params'}
      end

      it "assigns the requested quick_quote as @quick_quote" do
        quick_quote = QuickQuote.create! valid_attributes
        put :update, :id => quick_quote.id, :quick_quote => valid_attributes
        assigns(:quick_quote).should eq(quick_quote)
      end

      it "redirects to the quick_quote" do
        quick_quote = QuickQuote.create! valid_attributes
        put :update, :id => quick_quote.id, :quick_quote => valid_attributes
        response.should redirect_to(quick_quote)
      end
    end

    describe "with invalid params" do
      it "assigns the quick_quote as @quick_quote" do
        quick_quote = QuickQuote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuickQuote.any_instance.stub(:save).and_return(false)
        put :update, :id => quick_quote.id.to_s, :quick_quote => {}
        assigns(:quick_quote).should eq(quick_quote)
      end

      it "re-renders the 'edit' template" do
        quick_quote = QuickQuote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuickQuote.any_instance.stub(:save).and_return(false)
        put :update, :id => quick_quote.id.to_s, :quick_quote => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quick_quote" do
      quick_quote = QuickQuote.create! valid_attributes
      expect {
        delete :destroy, :id => quick_quote.id.to_s
      }.to change(QuickQuote, :count).by(-1)
    end

    it "redirects to the quick_quotes list" do
      quick_quote = QuickQuote.create! valid_attributes
      delete :destroy, :id => quick_quote.id.to_s
      response.should redirect_to(quick_quotes_url)
    end
  end

end
